#!/usr/bin/env bash
set -euo pipefail

# Generated by skills/sprint/scripts/sprint.py

echo "== Phase 1/3 =="
python3 skills/prompt-executor/scripts/executor.py --run --loop --max-iterations 3 --completion-marker VERIFICATION_COMPLETE --worktree --base-branch main --model claude agent-detection/012

echo "== Phase 2/3 =="
python3 skills/prompt-executor/scripts/executor.py --run --loop --max-iterations 3 --completion-marker VERIFICATION_COMPLETE --worktree --base-branch main --model claude agent-detection/013 agent-detection/014

echo "== Phase 3/3 =="
python3 skills/prompt-executor/scripts/executor.py --run --loop --max-iterations 3 --completion-marker VERIFICATION_COMPLETE --worktree --base-branch main --model claude agent-detection/015 agent-detection/016
python3 skills/prompt-executor/scripts/executor.py --run --loop --max-iterations 3 --completion-marker VERIFICATION_COMPLETE --worktree --base-branch main --model codex agent-detection/017
